build:
  version: "3.0"

accounts:
  message: "Welcome to MK accounts related local APIs "
  contactDetails:
    name: "Mahendra Kundare - Developer"
    email: "abc@mkbank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345