spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

loans:
  message: "Welcome to MK loans related QA APIs "
  contactDetails:
    name: "Mahendra Kundare - QA lead"
    email: "abc@mkbank.com"
  onCallSupport:
    - (785) 545-6565
    - (853) 546-3467