spring:
  application:
    name: "configserver"
  profiles:
    active: git
  #    active: native
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/mahendrakundare/mk-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
#        native:
#          search-locations: "file:///Users//mahendrakundare//Documents//config"
#          search-locations: "classpath:/config"

server:
  port: 8071

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"
