
build:
  version: "1.0"

accounts:
  message: "Welcome to MK accounts related PROD APIs "
  contactDetails:
    name: "Mahendra Kundare - Product owner"
    email: "abc@mkbank.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384